{
 "title": "Pachyderm Exporter",
 "description": "Dashboard for Pachyderm, using stats exported by https://github.com/button/pachyderm_exporter",
 "tags": [ "pachyderm" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   {
    "name": "pipeline",
    "query": "label_values(pachyderm_pipeline_states, pipeline)"
   },
   { "name": "range", "query": "1m,5m,10m,1h,1d" }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pachyderm Status",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "pachyderm_up" }
   ]
  },
  {
   "title": "Last Successful Job (UTC)",
   "type": "table",
   "gridPos": { "h": 6, "w": 11, "x": 2, "y": 1 },
   "targets": [
    {
     "expr": "pachyderm_last_successful_job * 1000"
    }
   ]
  },
  {
   "title": "Running Jobs",
   "type": "table",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 1 },
   "targets": [
    { "expr": "pachyderm_jobs_running" },
    { "expr": "pachyderm_jobs_starting" }
   ]
  },
  { "title": "$pipeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }, "repeat": "pipeline" },
  {
   "title": "Completed Jobs: $pipeline",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(pachyderm_jobs_completed_total{pipeline=\"$pipeline\"}[$range])",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Datums Processed: $pipeline",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(pachyderm_datums_total{pipeline=\"$pipeline\"}[$range])",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Datum Total Transfer Time: $pipeline",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(pachyderm_upload_time_seconds_total{pipeline=\"$pipeline\"}[$range])",
     "legendFormat": "upload"
    },
    {
     "expr": "increase(pachyderm_download_time_seconds_total{pipeline=\"$pipeline\"}[$range])",
     "legendFormat": "download"
    }
   ]
  },
  {
   "title": "Datum Total Transfer Size: $pipeline",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "increase(pachyderm_uploaded_bytes_total{pipeline=\"$pipeline\"}[$range])",
     "legendFormat": "upload"
    },
    {
     "expr": "increase(pachyderm_downloaded_bytes_total{pipeline=\"$pipeline\"}[$range])",
     "legendFormat": "download"
    }
   ]
  },
  { "title": "$pipeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Completed Jobs: $pipeline",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(pachyderm_jobs_completed_total{pipeline=\"$pipeline\"}[$range])",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Datums Processed: $pipeline",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(pachyderm_datums_total{pipeline=\"$pipeline\"}[$range])",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Datum Total Transfer Time: $pipeline",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(pachyderm_upload_time_seconds_total{pipeline=\"$pipeline\"}[$range])",
     "legendFormat": "upload"
    },
    {
     "expr": "increase(pachyderm_download_time_seconds_total{pipeline=\"$pipeline\"}[$range])",
     "legendFormat": "download"
    }
   ]
  },
  {
   "title": "Datum Total Transfer Size: $pipeline",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "increase(pachyderm_uploaded_bytes_total{pipeline=\"$pipeline\"}[$range])",
     "legendFormat": "upload"
    },
    {
     "expr": "increase(pachyderm_downloaded_bytes_total{pipeline=\"$pipeline\"}[$range])",
     "legendFormat": "download"
    }
   ]
  },
  { "title": "$pipeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Completed Jobs: $pipeline",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(pachyderm_jobs_completed_total{pipeline=\"$pipeline\"}[$range])",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Datums Processed: $pipeline",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(pachyderm_datums_total{pipeline=\"$pipeline\"}[$range])",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Datum Total Transfer Time: $pipeline",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(pachyderm_upload_time_seconds_total{pipeline=\"$pipeline\"}[$range])",
     "legendFormat": "upload"
    },
    {
     "expr": "increase(pachyderm_download_time_seconds_total{pipeline=\"$pipeline\"}[$range])",
     "legendFormat": "download"
    }
   ]
  },
  {
   "title": "Datum Total Transfer Size: $pipeline",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "increase(pachyderm_uploaded_bytes_total{pipeline=\"$pipeline\"}[$range])",
     "legendFormat": "upload"
    },
    {
     "expr": "increase(pachyderm_downloaded_bytes_total{pipeline=\"$pipeline\"}[$range])",
     "legendFormat": "download"
    }
   ]
  },
  { "title": "$pipeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Completed Jobs: $pipeline",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(pachyderm_jobs_completed_total{pipeline=\"$pipeline\"}[$range])",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Datums Processed: $pipeline",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(pachyderm_datums_total{pipeline=\"$pipeline\"}[$range])",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Datum Total Transfer Time: $pipeline",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(pachyderm_upload_time_seconds_total{pipeline=\"$pipeline\"}[$range])",
     "legendFormat": "upload"
    },
    {
     "expr": "increase(pachyderm_download_time_seconds_total{pipeline=\"$pipeline\"}[$range])",
     "legendFormat": "download"
    }
   ]
  },
  {
   "title": "Datum Total Transfer Size: $pipeline",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "increase(pachyderm_uploaded_bytes_total{pipeline=\"$pipeline\"}[$range])",
     "legendFormat": "upload"
    },
    {
     "expr": "increase(pachyderm_downloaded_bytes_total{pipeline=\"$pipeline\"}[$range])",
     "legendFormat": "download"
    }
   ]
  },
  { "title": "$pipeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Completed Jobs: $pipeline",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(pachyderm_jobs_completed_total{pipeline=\"$pipeline\"}[$range])",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Datums Processed: $pipeline",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(pachyderm_datums_total{pipeline=\"$pipeline\"}[$range])",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Datum Total Transfer Time: $pipeline",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(pachyderm_upload_time_seconds_total{pipeline=\"$pipeline\"}[$range])",
     "legendFormat": "upload"
    },
    {
     "expr": "increase(pachyderm_download_time_seconds_total{pipeline=\"$pipeline\"}[$range])",
     "legendFormat": "download"
    }
   ]
  },
  {
   "title": "Datum Total Transfer Size: $pipeline",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "increase(pachyderm_uploaded_bytes_total{pipeline=\"$pipeline\"}[$range])",
     "legendFormat": "upload"
    },
    {
     "expr": "increase(pachyderm_downloaded_bytes_total{pipeline=\"$pipeline\"}[$range])",
     "legendFormat": "download"
    }
   ]
  }
 ]
}