{
 "title": "VM's on server",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "domain",
    "query": "label_values( libvirt_domain_info_virtual_cpus{job=\"libvirt_exporter\"}, domain)"
   }
  ]
 },
 "panels": [
  { "title": "$domain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "domain" },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "libvirt_domain_info_virtual_cpus{domain=\"[[domain]]\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "libvirt_domain_info_maximum_memory_bytes{domain=\"[[domain]]\"}+.5e9",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 11, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(avg by (instance) (irate(libvirt_domain_info_cpu_time_seconds_total{domain=\"[[domain]]\"}[5m])) * 100)",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  { "title": "$domain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "libvirt_domain_info_virtual_cpus{domain=\"[[domain]]\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "libvirt_domain_info_maximum_memory_bytes{domain=\"[[domain]]\"}+.5e9",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 11, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(avg by (instance) (irate(libvirt_domain_info_cpu_time_seconds_total{domain=\"[[domain]]\"}[5m])) * 100)",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  { "title": "$domain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "libvirt_domain_info_virtual_cpus{domain=\"[[domain]]\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 9 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "libvirt_domain_info_maximum_memory_bytes{domain=\"[[domain]]\"}+.5e9",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 11, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(avg by (instance) (irate(libvirt_domain_info_cpu_time_seconds_total{domain=\"[[domain]]\"}[5m])) * 100)",
     "legendFormat": "{{domain}}"
    }
   ]
  }
 ]
}